version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "my-postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "tinywiny_network"
    ports:
      - "35432:5432"
  localstack:
    container_name: "LocalStack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Edge Port
      - "4572:4572" # S3 Port
    environment:
      - SERVICES:s3brew
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/docker-entrypoint-initaws.d

