spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/tinywiny_network
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
aws:
  region: "us-east-1"
  s3:
    endpoint: http://Localhost:4566
  image-placeholder-path: /static/images/empty.png
management:
  endpoints:
    web:
      exposure:
        include: '*'
jwt:
  secretKey: secretKeyNika

logging:
  level:
    org:
      hibernate:
        type: trace