spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/tinywiny_network

aws:
  region: "us-east-1"
  s3:
    endpoint: http://Localhost:4566
  image-placeholder-path: /static/images/empty.png
management:
  endpoints:
    web:
      exposure:
        include: '*'
security:
  secretKey: "secretKeyNika"
  refresh_secret: "secretRefresh"
  allowed-origin: "http://localhost:3000"
  session-duration-minutes: 86400

jwt:
  access_token_name: "JWT"
  refresh_token_name: "JWT_REFRESH"

csrf:
  xsrf_cookie_name: 'XSRF'
  xsrf_header_name: "X-XSRF"
  cookie_domain: "localhost"

logging:
  level:
    org:
      hibernate:
        type: trace